# Introduction to some Python stuff

The main purpose of this file is to follow the ideas in "Introduction to R" by Marius Hofert and present similar concepts that exist in python. Not everything can be translated in a one-to-one fashion as, unlike R, python is not inherently build for mathematical work. Some packages will need to be imported to make things work. It is assumed here that the user is familiar with basic use of python. If you are not familiar with python at all, then there are great free resources on python for beginners such as: [w3schools](https://www.w3schools.com/python/), or the [Open CS course](https://open.cs.uwaterloo.ca/python-from-scratch/) from the University of Waterloo.

## Important Imports

Naturally, some packages need to be imported. We will start with the basic packages such as numpy, pandas, matplotlib, and so on, and will only import packages as needed.

In [1]:
import numpy as np # For dealing with vectors
import pandas as pd # For dealing with dataframes

# For dealing with plots
import matplotlib as mpl
import matplotlib.pyplot as plt

## Simple Manipulations

### Numbers

In [2]:
1/2

0.5

In [3]:
1/0

ZeroDivisionError: division by zero

May be better to use np.divide, but it may be cumbersome to do this everytime. Recommend using np.divide if suspected division be zero.

In [4]:
np.divide(1, 2)

0.5

In [5]:
np.divide(1, 0) # Notice the warning. Also, not the output

/tmp/wsuser/ipykernel_164/2388086987.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, 0)


inf

In [7]:
np.divide(-1, 0) # Note np.divide(1, -0) actually gives inf, and not -inf. This is unlike 1/-0 in R

/tmp/wsuser/ipykernel_164/1794806404.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(-1, 0)


-inf

In [8]:
np.divide(0, 0)

/tmp/wsuser/ipykernel_164/2105560962.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.divide(0, 0)


nan

In [13]:
x = np.divide(0, 0)
type(x) # Note the use of type(x) instead of class(x)

## Relevant: https://www.quora.com/What-is-the-Python-equivalent-of-R-programmings-class-function

/tmp/wsuser/ipykernel_164/1695779124.py:1: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(0, 0)


numpy.float64

In [16]:
type(np.inf)

float

In [17]:
np.inf

inf

### Vectors (a.k.a numpy arrays)

There is no built-in vector type in python. If using the R-package "reticulate" to convert "r_to_py", then single element R-vectors are turned into floats, and multi-element R-vectors are turned into python lists, as seen in the following [blog](https://www.r-bloggers.com/2020/01/what-r-you-in-python-r-vectors/). Here, using np.arrays is recommended for their similarities in dealing with R-vectors.

In [20]:
x = np.array([1, 2, 3, 4, 5])
type(x) # Note that x is an ndarray

numpy.ndarray

In [23]:
x.size # Not length(x)

5

In [25]:
x

array([1, 2, 3, 4, 5])

In [33]:
# Other ways of creating similar arrays
y = np.array(range(1, 6)) # Note that the last number is one more that what is needed
y

array([1, 2, 3, 4, 5])

In [34]:
# Or better yet
z = np.arange(1, 6)
z

array([1, 2, 3, 4, 5])

In [37]:
z[0] # Indexing starts at 0

1

In [38]:
#This doesn't work
z[5] = 6

IndexError: index 5 is out of bounds for axis 0 with size 5

In [40]:
#use append instead
z = np.append(z, 6) # Note that np.append is not Inplace
z

array([1, 2, 3, 4, 5, 6])

In [42]:
x == y # Compares which elements of x match elements of y with same index, does not compare if x and y are the same

array([ True,  True,  True,  True,  True])

In [43]:
np.equal(x, y) # Does the same as above

array([ True,  True,  True,  True,  True])

In [46]:
# Check if x and y are the same ndarray
np.array_equal(x, y)

True

It is also possible to do the above using "(x == y).all()", but there are some issues with it as discussed [here](https://www.codingem.com/numpy-compare-arrays/).

In [48]:
(x == y).all()

True

### Watch out

In [49]:
x = np.var(np.arange(1,5))
y = np.std(np.arange(1, 5))**2

In [50]:
x == y # Not the same

False

In [53]:
x - y # Numerically not zero

-2.220446049250313e-16

In [54]:
x

1.25

In [55]:
y

1.2500000000000002

In [57]:
n = 0
np.arange(1, n) # empty array, some dissimilarities with R

array([], dtype=int64)

In [58]:
np.arange(2, n) # also empty array

array([], dtype=int64)

In [59]:
n = -1
np.arange(1, n) # also empty array

array([], dtype=int64)

In [62]:
# Couldn't find anything directly equivalent to R's seq_along, but here is a possible alternate
np.arange(1, np.array([3, 4, 2]).size + 1)

array([1, 2, 3])

### Some functions

In [63]:
x = np.array([3, 4, 2])

In [64]:
x.size

3

In [68]:
np.flip(x)

array([2, 4, 3])

In [69]:
np.sort(x)

array([2, 3, 4])

In [71]:
# there is no option or argument in both the sort() functions to change the sorting order to decreasing order.
#So, to sort a numpy array in descending order we need to sort it and then use [::-1] to reverse the sorted array.
np.sort(x)[::-1]

array([4, 3, 2])

In [72]:
#Returns the indices that would sort an array.
np.argsort(x)

array([2, 0, 1])

In [73]:
x[np.argsort(x)] # Returns sort(x)

array([2, 3, 4])

In [75]:
np.log(x) # natural logarithms

array([1.09861229, 1.38629436, 0.69314718])

In [76]:
x**2 # component=wise squares

array([ 9, 16,  4])

In [77]:
np.sum(x) # sum all numbers

9

In [78]:
np.cumsum(x) # compute the cumulative sum

array([3, 7, 9])

In [79]:
np.prod(x) # multiply all numbers

24

In [80]:
np.arange(1, 8, step = 2)

array([1, 3, 5, 7])

In [81]:
np.repeat(np.arange(1,4), 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [83]:
# To make it repeat a number of times, use np.tile
np.tile(np.repeat(np.arange(1,4), 3), 2)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1, 2, 2, 2, 3, 3, 3])

In [86]:
x[-1] # to get the last element of a vector

2

In [87]:
x[:-1] # to get everything but the last element

array([3, 4])